crypto: add proper const attributes, change arc4_crypt interface
Add proper const attribute to function arguments in
crypto algorithms (aes, des, arc4, camellia, xtea)

Change interface of arc4_crypt to have separate
input and output buffers.

const attribute is added to function arguments and
variables in order to allow compiler checks with
-Wbad-function-cast, -Wcast-qual and
-Wwrite-strings warnings options.

Fix unused parameter warning in camellia_crypt_ecb(). The
following warning was reported with -Wextra:

  camellia.c: In function ‘camellia_crypt_ecb’:
  camellia.c:511: error: unused parameter ‘mode’

Make camellia_feistel() static. This fixes the following
warning with -Wmissing-declarations:

  camellia.c:325: warning: no previous declaration for
  ‘camellia_feistel’

Add xtea_crypt_ecb declaration. This fixes this warning
shown with -Wmissing-declarations:

  xtea.c:82: warning: no previous declaration for
  ‘xtea_crypt_ecb’

Separate input and output buffers in xtea_self_test().